### ISSUE TITLE
H*W or W*H?

### ISSUE THREAD

**Issue by caiyongqi** [apchenstu/mvsnerf#53]
Hi. `src_grid = src_grid.view(B, D, W_pad, H_pad, 2)` in function homo_warp. The shape of src_grid seems to be (B, D*H*W, 2), so is there something wrong with the above code?

**Comment by apchenstu** [comment]
Thanks! That's right it should be `src_grid = src_grid.view(B, D, H_pad, W_pad, 2)`, but looks like this bug would not affect the final results since the following [code](https://github.com/apchenstu/mvsnerf/blob/597f5585464dc2c47b50b4de83c3843e9e2dcdc1/utils.py#L625) reshape the src_grid to (B, D, W_pad * H_pad, 2) which is orderless.

**Comment by caiyongqi** [comment]
Yes, you are right. Thanks for your reply!
